name: LobbySystem
version: ${project.version}
main: me.iloveeatmuffin.lobbysystem.LobbySystem
api-version: 1.13
authors: [ILoveEatMuffin]
description: 大廳插件
commands:
  fly:
    description: 飛行指令
    usage: /<command>
  speed:
    description: 速度指令
    usage: /<command>
  hide:
    description: 隱藏指令
    usage: /<command>
  globalmute:
    description: 禁用聊天室指令
    usage: /<command>





